Add MWE (#2)
* wip

* also lint css

* better

* rename

* node 16

* asd

* wip

* wip

* wip

* move

* so?

Error: Error parsing stylelint JSON output: Unexpected end of JSON input. Output: ""

* anscheinend nicht

* scheiss doch die wand an

* move to separate step

* so?

* so?

* add colours from powerpoint

* add fonts

* kebap-case

* modern colours

* uio